### ISSUE TITLE
Login not saved

### ISSUE THREAD

**Issue by pulasthieka** [pulasthieka/careerfair#6]
Login page just redirects the user, the login details are not saved. No authentication token is generated. This will create issues with features that depend on authentication like:

1. AuthGuards for routing
2. Firebase requests have to be authenticated for Firebase rules
3. Page refresh resets the Angular application and will log out the person.

**Comment by pulasthieka** [comment]
@bumuthu take a look at this

**Comment by bumuthu** [comment]
Apart from Firebase rules, all others are done.
